export const PROPERTY_LIST_REQUEST = 'PROPERTY_LIST_REQUEST';
export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL';

export const SEARCH_SET_LOCATION = 'SEARCH_SET_LOCATION';
export const SEARCH_SET_DATES = 'SEARCH_SET_DATES';
export const SEARCH_SET_GUESTS = 'SEARCH_SET_GUESTS';
